name: chokchey_finance
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  http: ^0.12.0+3
  flutter_secure_storage: ^3.3.3
  bottom_navy_bar: ^5.4.0
  jiffy: ^3.0.1
  firebase_auth: ^0.18.0+1
  firebase_database: ^4.0.0
  flutter_form_builder: ^3.14.1
  provider: ^4.1.3
  intl: ^0.16.1
  path_provider: ^1.6.11
  flutter_full_pdf_viewer: ^1.0.6
  file_picker: ^1.13.0
  flutter_datetime_picker: ^1.3.8
  cupertino_icons: ^0.1.3
  geolocator: ^5.1.3
  select_dialog: ^1.2.1
  permission_handler: ^5.0.1+1
  flutter_spinkit: "^4.1.2"
  multi_image_picker: ^4.6.7
  image_picker: ^0.6.7+4
  pdf_flutter: ^1.1.2
  awesome_dialog: ^1.1.2
  sticky_headers: ^0.1.8+1
  dio: ^3.0.10
  logger: ^0.9.2
  flutter_chips_input: ^1.9.1
  firebase_messaging: ^7.0.0
  firebase_core: ^0.5.0
  photo_view: ^0.10.2
  charts_flutter: ^0.9.0
  url_launcher: ^5.7.2
  slide_popup_dialog: ^0.0.2
  multi_select_item: ^1.0.3
  flutter_money_formatter:
    git:
      url: git://github.com/anisalibegic/flutter_money_formatter.git
  smart_select: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"
  json_model:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon/1024.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon/1024.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/.
    - lang/en.json
    - lang/km.json
    - assets/pdf/
    - assets/images/list.png
    - assets/images/percentage.png
    - assets/pdf/requirementchecklist.pdf

    - assets/images/101.png
    - assets/images/102.png
    - assets/images/103.png
    - assets/images/104.png

    - assets/images/211.png
    - assets/images/212.png
    - assets/images/213.png
    - assets/images/214.png
    - assets/images/215.png
    - assets/images/216.png

    - assets/images/221.png
    - assets/images/222.png
    - assets/images/223.png
    - assets/images/224.png
    - assets/images/225.png
    - assets/images/226.png
    - assets/images/227.png
    - assets/images/228.png

    - assets/images/301.png
    - assets/images/302.png
    - assets/images/english.png
    - assets/images/khmer.png

  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
