name: chokchey_finance
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# version: 1.2.3+5
version: 1.3.2

environment:
  sdk: ">=2.12.2 <3.0.0"
  # sdk: ">=2.13.4 <3.0.0"

dependencies:
  platform: ^3.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  http: ^0.13.1
  flutter_secure_storage: ^3.3.3
  bottom_navy_bar: ^5.4.0
  firebase_auth: ^1.0.0
  firebase_database: ^7.0.0-dev.1
  flutter_form_builder: ^6.0.0-nullsafety.1
  provider: ^6.0.0
  intl: ^0.17.0
  path_provider: ^2.0.0-nullsafety
  file_picker: ^4.2.7
  flutter_datetime_picker: ^1.3.8
  cupertino_icons: ^1.0.2
  geolocator: ^8.1.0
  select_dialog: ^1.2.1
  permission_handler: ^6.0.1
  flutter_spinkit: "^4.1.2"
  multi_image_picker: ^4.6.7
  image_picker: ^0.8.2
  awesome_dialog: ^1.1.2
  sticky_headers: ^0.1.8+1
  dio: ^4.0.0-prev3
  logger: ^0.9.2
  flutter_chips_input: ^1.9.1
  firebase_messaging: ^9.0.0
  firebase_core: ^1.0.2
  photo_view: ^0.10.2
  charts_flutter: ^0.12.0
  url_launcher: ^6.0.10
  slide_popup_dialog: ^0.0.2
  multi_select_item: ^1.0.3
  package_info: ^2.0.0
  smart_select: ^4.3.2
  group_list_view: ^1.0.6
  # call_log: ^2.0.2
  webview_flutter: ^2.0.9
  epub_viewer: ^0.2.4
  geocoding: ^2.0.4
  multi_select_flutter: ^4.1.2
  autocomplete_textfield: ^1.7.3
  syncfusion_flutter_pdfviewer: ^19.4.56-beta
  dropdown_search: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  # json_model:
  # build_runner: ^1.12.2
  # json_serializable: ^2.0.0
  # logging: ^0.11.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon/1024.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon/1024.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/.
    - lang/en.json
    - lang/km.json
    - assets/pdf/
    - assets/images/list.png
    - assets/images/percentage.png
    - assets/pdf/requirementchecklist.pdf

    - assets/images/101.png
    - assets/images/102.png
    - assets/images/103.png
    - assets/images/104.png

    - assets/images/211.png
    - assets/images/212.png
    - assets/images/213.png
    - assets/images/214.png
    - assets/images/215.png
    - assets/images/216.png

    - assets/images/221.png
    - assets/images/222.png
    - assets/images/223.png
    - assets/images/224.png
    - assets/images/225.png
    - assets/images/226.png
    - assets/images/227.png
    - assets/images/228.png

    - assets/images/301.png
    - assets/images/302.png
    - assets/images/english.png
    - assets/images/khmer.png
    - assets/images/phonecall.png
    - assets/Credit_Operation_Manual.pdf
    - assets/images/khm.png

  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
